import {
    Home,
    SlidersHorizontal,
    Shield,
    Users,
    Building2,
    BookOpen,
    Package,
    Tags,
    BadgeDollarSign,
    Ruler,
    ShoppingCart,
    Truck,
    FileText,
    FilePlus2,
    PackageCheck,
    Warehouse,
    ArrowLeftRight,
    ClipboardCheck,
    ShoppingBag,
    Contact,
    ReceiptText,
    Store,
    Repeat,
    Scale,
    Handshake,
    Wallet,
    CreditCard,
    Coins,
    ArrowRightLeft,
    HandCoins,
    Receipt,
} from 'lucide-react';

export const navigation = [
    { label: 'Inicio', icon: Home, to: '/dashboard' },
    {
        label: 'Ventas',
        icon: ShoppingBag,
        children: [
            { label: 'Clientes', icon: Contact, to: '/clientes' },
            { label: 'Notas de Venta', icon: ReceiptText, to: '/notas-venta' },
        ],
    },
    {
        label: 'Catálogo',
        icon: BookOpen,
        children: [
            { label: 'Productos', icon: Package, to: '/productos' },
            { label: 'Categorías', icon: Tags, to: '/categorias' },
            { label: 'Marcas', icon: BadgeDollarSign, to: '/marcas' },
            { label: 'Sub-marcas', icon: BadgeDollarSign, to: '/sub-marcas' },
            { label: 'Unidades de medida', icon: Ruler, to: '/unidades-medida' },
        ],
    },
    {
        label: 'Compras',
        icon: ShoppingCart,
        children: [
            { label: 'Proveedores', icon: Truck, to: '/proveedores' },
            { label: 'Órdenes de compra', icon: FileText, to: '/ordenes-compra' },
            { label: 'Solicitudes de compra', icon: FilePlus2, to: '/solicitudes-compra' },
            { label: 'Recepciones de compra', icon: PackageCheck, to: '/recepciones-compra' },
        ],
    },
    {
        label: 'Inventario',
        icon: Warehouse,
        children: [
            { label: 'Almacenes', icon: Store, to: '/almacenes' },
            { label: 'Existencias', icon: Warehouse, to: '/existencias' },
            { label: 'Movimientos', icon: ArrowLeftRight, to: '/movimientos' },
            { label: 'Traslados', icon: Repeat, to: '/transferencias' },
            { label: 'Ajustes', icon: Scale, to: '/ajustes' },
            { label: 'Tomas de inventario', icon: ClipboardCheck, to: '/tomas-inventario' },
            { label: 'Préstamos', icon: Handshake, to: '/prestamos' },
        ],
    },
    {
        label: 'Tesorería',
        icon: Wallet,
        children: [
            { label: 'Cuentas y Medios de Pago', icon: CreditCard, to: '/metodos-de-pago' },
            { label: 'Cajas', icon: Coins, to: '/cajas' },
            { label: 'Movimientos de Caja', icon: ArrowRightLeft, to: '/movimientos-caja' },
            { label: 'Cuentas por Cobrar', icon: HandCoins, to: '/cuentas-por-cobrar' },
            { label: 'Cuentas por Pagar', icon: Receipt, to: '/cuentas-por-pagar' },
        ],
    },
    {
        label: 'Gestión',
        icon: SlidersHorizontal,
        children: [
            { label: 'Roles', icon: Shield, to: '/roles' },
            { label: 'Usuarios', icon: Users, to: '/usuarios' },
            { label: 'Empresa', icon: Building2, to: '/empresa' },
        ],
    },
];
